/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_mndk_scjdmc_cdtlib_Triangulation */

#ifndef _Included_com_mndk_scjdmc_cdtlib_Triangulation
#define _Included_com_mndk_scjdmc_cdtlib_Triangulation
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_mndk_scjdmc_cdtlib_Triangulation
 * Method:    construct
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_mndk_scjdmc_cdtlib_Triangulation_construct__
  (JNIEnv *, jobject);

/*
 * Class:     com_mndk_scjdmc_cdtlib_Triangulation
 * Method:    construct
 * Signature: (Lcom/mndk/scjdmc/cdtlib/VertexInsertionOrder;)V
 */
JNIEXPORT void JNICALL Java_com_mndk_scjdmc_cdtlib_Triangulation_construct__Lcom_mndk_scjdmc_cdtlib_VertexInsertionOrder_2
  (JNIEnv *, jobject, jobject);

/*
 * Class:     com_mndk_scjdmc_cdtlib_Triangulation
 * Method:    construct
 * Signature: (Lcom/mndk/scjdmc/cdtlib/VertexInsertionOrder;Lcom/mndk/scjdmc/cdtlib/IntersectingConstraintEdges;D)V
 */
JNIEXPORT void JNICALL Java_com_mndk_scjdmc_cdtlib_Triangulation_construct__Lcom_mndk_scjdmc_cdtlib_VertexInsertionOrder_2Lcom_mndk_scjdmc_cdtlib_IntersectingConstraintEdges_2D
  (JNIEnv *, jobject, jobject, jobject, jdouble);

/*
 * Class:     com_mndk_scjdmc_cdtlib_Triangulation
 * Method:    destruct
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_mndk_scjdmc_cdtlib_Triangulation_destruct
  (JNIEnv *, jobject);

/*
 * Class:     com_mndk_scjdmc_cdtlib_Triangulation
 * Method:    getVertices
 * Signature: ()Ljava/util/List;
 */
JNIEXPORT jobject JNICALL Java_com_mndk_scjdmc_cdtlib_Triangulation_getVertices
  (JNIEnv *, jobject);

/*
 * Class:     com_mndk_scjdmc_cdtlib_Triangulation
 * Method:    getVerticesCount
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_mndk_scjdmc_cdtlib_Triangulation_getVerticesCount
  (JNIEnv *, jobject);

/*
 * Class:     com_mndk_scjdmc_cdtlib_Triangulation
 * Method:    getIndexedTriangles
 * Signature: ()Ljava/util/List;
 */
JNIEXPORT jobject JNICALL Java_com_mndk_scjdmc_cdtlib_Triangulation_getIndexedTriangles
  (JNIEnv *, jobject);

/*
 * Class:     com_mndk_scjdmc_cdtlib_Triangulation
 * Method:    getTrianglesCount
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_mndk_scjdmc_cdtlib_Triangulation_getTrianglesCount
  (JNIEnv *, jobject);

/*
 * Class:     com_mndk_scjdmc_cdtlib_Triangulation
 * Method:    getFixedEdges
 * Signature: ()Ljava/util/Set;
 */
JNIEXPORT jobject JNICALL Java_com_mndk_scjdmc_cdtlib_Triangulation_getFixedEdges
  (JNIEnv *, jobject);

/*
 * Class:     com_mndk_scjdmc_cdtlib_Triangulation
 * Method:    insertVertices
 * Signature: (Ljava/util/List;)V
 */
JNIEXPORT void JNICALL Java_com_mndk_scjdmc_cdtlib_Triangulation_insertVertices
  (JNIEnv *, jobject, jobject);

/*
 * Class:     com_mndk_scjdmc_cdtlib_Triangulation
 * Method:    insertEdges
 * Signature: (Ljava/util/List;)V
 */
JNIEXPORT void JNICALL Java_com_mndk_scjdmc_cdtlib_Triangulation_insertEdges
  (JNIEnv *, jobject, jobject);

/*
 * Class:     com_mndk_scjdmc_cdtlib_Triangulation
 * Method:    conformToEdges
 * Signature: (Ljava/util/List;)V
 */
JNIEXPORT void JNICALL Java_com_mndk_scjdmc_cdtlib_Triangulation_conformToEdges
  (JNIEnv *, jobject, jobject);

/*
 * Class:     com_mndk_scjdmc_cdtlib_Triangulation
 * Method:    eraseSuperTriangle
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_mndk_scjdmc_cdtlib_Triangulation_eraseSuperTriangle
  (JNIEnv *, jobject);

/*
 * Class:     com_mndk_scjdmc_cdtlib_Triangulation
 * Method:    eraseOuterTriangles
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_mndk_scjdmc_cdtlib_Triangulation_eraseOuterTriangles
  (JNIEnv *, jobject);

/*
 * Class:     com_mndk_scjdmc_cdtlib_Triangulation
 * Method:    eraseOuterTrianglesAndHoles
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_mndk_scjdmc_cdtlib_Triangulation_eraseOuterTrianglesAndHoles
  (JNIEnv *, jobject);

/*
 * Class:     com_mndk_scjdmc_cdtlib_Triangulation
 * Method:    initializedWithCustomSuperGeometry
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_mndk_scjdmc_cdtlib_Triangulation_initializedWithCustomSuperGeometry
  (JNIEnv *, jobject);

/*
 * Class:     com_mndk_scjdmc_cdtlib_Triangulation
 * Method:    isFinalized
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_com_mndk_scjdmc_cdtlib_Triangulation_isFinalized
  (JNIEnv *, jobject);

/*
 * Class:     com_mndk_scjdmc_cdtlib_Triangulation
 * Method:    calculateTriangleDepths
 * Signature: ()S
 */
JNIEXPORT jshort JNICALL Java_com_mndk_scjdmc_cdtlib_Triangulation_calculateTriangleDepths
  (JNIEnv *, jobject);

/*
 * Class:     com_mndk_scjdmc_cdtlib_Triangulation
 * Method:    flipEdge
 * Signature: (II)V
 */
JNIEXPORT void JNICALL Java_com_mndk_scjdmc_cdtlib_Triangulation_flipEdge
  (JNIEnv *, jobject, jint, jint);

/*
 * Class:     com_mndk_scjdmc_cdtlib_Triangulation
 * Method:    removeTriangles
 * Signature: (Ljava/util/Set;)V
 */
JNIEXPORT void JNICALL Java_com_mndk_scjdmc_cdtlib_Triangulation_removeTriangles
  (JNIEnv *, jobject, jobject);

#ifdef __cplusplus
}
#endif
#endif
